spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_mngr
    username: root
    password: zugravul70
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
